services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus@sha256:82bb24e3e06c60145789c95653b187f9b73fe7012489a756a0c4fa490a7829f6 # prom/prometheus:v3.10.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana@sha256:fab4d86718ecf6aec45961ae01c5f743a955e11fad0adb8f43c5f52a961b5144 # grafana/grafana:12.4.1
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - monitoring

  k6:
    image: grafana/k6@sha256:7964002c5c013ec7ad84182b028fca2666dcb8baba2c5c19b3e5e4f0f412d019 # grafana/k6:1.6.0
    volumes:
      - ./k6:/scripts
    command: run /scripts/script.js
    depends_on:
      - app
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
