name: GitHub Actions Pin Check

on:
  push:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  pin-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3.6.3
      - name: Pin check
        run: |
          pinact run --check
